#!/bin/sh

# alvs       Manages ALVS daemon
#
### BEGIN INIT INFO
# Provides:          ALVS
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description: Starts ALVS daemon
# short-description: ALVS daemon
### END INIT INFO

LC_APP_NAME=alvs
UC_APP_NAME=ALVS

# Source common service configuration file
. /usr/share/alvs/service.init

