#!/bin/sh
# postrm script for alvs
#
# see: dh_installdeb(1)

# summary of how this script can be called:
#		* <postrm> `remove'
#		* <postrm> `purge'
#		* <old-postrm> `upgrade' <new-version>
#		* <new-postrm> `failed-upgrade' <old-version>
#		* <new-postrm> `abort-install'
#		* <new-postrm> `abort-install' <old-version>
#		* <new-postrm> `abort-upgrade' <old-version>
#		* <disappearer's-postrm> `disappear' <overwriter>
#		  <overwriter-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

######################################
# Definitions
######################################
ALVS_NPS_IP='169.254.42.44'
ALVS_NPS_HOST='alvs_nps'


######################################
# ALVS utiles
######################################
#-------------------------------------------------------------------------------
remove_line_from_file()
{
	if [ $# -ne 2 ]; then
		echo "ERROR: remove_line_from_file: number of args ($#) is wrong. expect <line> <file name>"
		exit 1
	fi

	cmd=$1
	filename=$2
	tmpfile=$filename".tmp"
	
	if [ -e $filename ]; then
		# remove command from file
		cat $filename | grep -v "$cmd" > $tmpfile
		cat $tmpfile > $filename
		rm -f $tmpfile
	fi
}

#-------------------------------------------------------------------------------
remove_alvs_on_boot()
{
	cmd="/etc/init.d/alvs start"
	filename="/etc/rc.local"
	
	remove_line_from_file "$cmd" $filename
}

#-------------------------------------------------------------------------------
remove_nps_host()
{
	cmd="$ALVS_NPS_IP   $ALVS_NPS_HOST"
	filename="/etc/hosts"
	
	remove_line_from_file "$cmd" $filename
}

#-------------------------------------------------------------------------------
reload_configuration()
{
	systemctl daemon-reload > /dev/null 2>&1
	service rsyslog restart > /dev/null 2>&1
	sysctl -a > /dev/null 2>&1
	service networking restart > /dev/null 2>&1
}


######################################
# Main
######################################
filename=$(basename $0)

case "$1" in
	remove)
	remove_alvs_on_boot
	remove_nps_host
	reload_configuration
	;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	
	;;

	*)
		echo "$filename called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0
