#!/bin/sh
# postinst script for alvs
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#		* <postinst> `configure' <most-recently-configured-version>
#		* <old-postinst> `abort-upgrade' <new version>
#		* <conflictor's-postinst> `abort-remove' `in-favour' <package>
#		  <new-version>
#		* <postinst> `abort-remove'
#		* <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#		  <failed-install-package> <version> `removing'
#		  <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


######################################
# Definitions
######################################
ALVS_NPS_IP='169.254.42.44'
ALVS_NPS_HOST='alvs_nps'



######################################
# ALVS utiles
######################################

#-------------------------------------------------------------------------------
configure_alvs_on_boot()
{
	cmd="/etc/init.d/alvs start"
	filename="/etc/rc.local"
	tmpfile="/etc/rc.local.tmp"
	
	if [ -e $filename ]; then
		# check if command already exits
		res=$(cat $filename | grep "$cmd" | wc -l)
		if [ $res -ne 1 ]; then
			# remove "exit 0" from file
			cat $filename | grep -v "exit 0" > $tmpfile
			cat $tmpfile > $filename
			rm -f $tmpfile
			
			# add commnad
			echo "$cmd" >> $filename
			
			# restor "exit 0"
			echo "exit 0" >> $filename
		fi	
	else
		# add commnad
		echo "$cmd" > $filename
		
		# restore "exit 0"
		echo "exit 0" >> $filename
	fi
	return 0
}

#-------------------------------------------------------------------------------
add_nps_host()
{
	res=$(cat /etc/hosts | grep $ALVS_NPS_IP | wc -l)
	if [ $res -ne 1 ]; then
		echo "$ALVS_NPS_IP   $ALVS_NPS_HOST" >> /etc/hosts
	fi
	return 0
}

#-------------------------------------------------------------------------------
reload_configuration()
{
	systemctl daemon-reload > /dev/null 2>&1
	[ "$?" = 0 ] && service rsyslog restart > /dev/null 2>&1
	[ "$?" = 0 ] && sysctl -p /etc/sysctl.d/alvs.conf > /dev/null 2>&1
	[ "$?" = 0 ] && service networking restart > /dev/null 2>&1
	return $?
}

#-------------------------------------------------------------------------------
start_alvs()
{
	echo " Starting alvs service"
	service alvs start
	return 0
}



######################################
# Main
######################################
filename=$(basename $0)

rc=0
case "$1" in
	configure|abort-upgrade)
		[ "$?" = 0 ] && configure_alvs_on_boot
		[ "$?" = 0 ] && add_nps_host
		[ "$?" = 0 ] && reload_configuration
		[ "$?" = 0 ] && start_alvs
		rc=$?
	;;

	abort-remove|abort-deconfigure)
		echo "WARNING: $filename called with unsupported argument \`$1'" >&2
	;;

	*)
		echo "$filename called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

if [ $rc -ne 0 ]; then
	echo "ERROR: $filename failed"
fi
exit $rc

