#-------------------------------------------------------
#This file was automatically generated by EZConfigExport
#-------------------------------------------------------

def created(cpe):
    cpe.cp.channel.set_int_mem_space_params(index=2, enable=True, type='1_CLUSTER_DATA', size=128)
    cpe.cp.channel.set_int_mem_space_params(index=3, enable=True, type='1_CLUSTER_CODE', size=64)
    cpe.cp.channel.set_eth_if_params(side=0, if_engine=0, eth_if_type='10GE', if_number=0, rx_enable=True, tx_enable=True, tx_tm_bypass=True)
    return True

def powered_up(cpe):
    return True

def initialized(cpe):
    return True

def finalized(cpe):
    return True

def running(cpe):
    return True

