#-------------------------------------------------------
#This file was automatically generated by EZConfigExport
#-------------------------------------------------------

def add_entries(cpe):
    return True

